# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-11 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='城市名称')),
                ('pid', models.ForeignKey(max_length=11, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.City')),
            ],
        ),
    ]
