# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='地点id')),
                ('type', models.IntegerField(choices=[(0, '行政区'), (1, '高校'), (2, '火车站'), (3, '景点'), (4, '机场'), (5, '医院'), (6, '购物广场'), (7, '商圈')], verbose_name='地点类型')),
                ('pinyin', models.CharField(max_length=100, verbose_name='拼音')),
                ('name', models.CharField(max_length=100, verbose_name='地点名称')),
                ('radius', models.IntegerField(verbose_name='范围')),
                ('latitude', models.IntegerField(verbose_name='维度')),
                ('longitude', models.IntegerField(verbose_name='经度')),
                ('city', models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.CASCADE, to='house.City', verbose_name='城市')),
            ],
        ),
    ]
