# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_siteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='cityname',
            field=models.CharField(default='no', max_length=100, verbose_name='城市名称'),
            preserve_default=False,
        ),
    ]
