# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_siteinfo_cityname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='latitude',
            field=models.IntegerField(null=True, verbose_name='维度'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='longitude',
            field=models.IntegerField(null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='radius',
            field=models.IntegerField(null=True, verbose_name='范围'),
        ),
    ]
