# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20190813_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
