# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0005_auto_20190813_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='房子类型')),
                ('introduce', models.TextField(verbose_name='房子标题、介绍')),
                ('facility', models.TextField(verbose_name='房子设施')),
                ('area', models.IntegerField(verbose_name='商圈')),
                ('limit', models.TextField(verbose_name='房客须知')),
                ('auto_reply', models.TextField(verbose_name='自动回复')),
                ('price', models.IntegerField(verbose_name='普通价格')),
                ('h_price', models.IntegerField(verbose_name='节假日价格')),
                ('info', models.TextField(verbose_name='房子详情')),
                ('discounts', models.TextField(verbose_name='优惠政策')),
                ('book', models.TextField(verbose_name='预订设置')),
                ('photo', models.TextField(verbose_name='照片')),
                ('city', models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.CASCADE, to='house.City', verbose_name='城市')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.SiteInfo', verbose_name='行政区')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='房东')),
            ],
        ),
    ]
