# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-15 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_houseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='title',
            field=models.TextField(default='--', verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='introduce',
            field=models.TextField(verbose_name='房子介绍'),
        ),
    ]
