# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-14 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0008_auto_20190815_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=11, verbose_name='订单号')),
                ('date', models.DateField(verbose_name='订单日期')),
                ('price', models.FloatField(max_length=10, verbose_name='价格')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='消费者')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.HouseInfo', verbose_name='房源')),
            ],
        ),
    ]
