# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-19 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='订单日期')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.HouseInfo', verbose_name='房源')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_num',
            field=models.IntegerField(default=1, verbose_name='入住人数'),
        ),
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='订单结束日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='liuyan',
            field=models.TextField(null=True, verbose_name='liuyan'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='订单开始日期'),
            preserve_default=False,
        ),
    ]
