# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-22 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_auto_20200319_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='evalute',
            field=models.TextField(null=True, verbose_name='评价'),
        ),
        migrations.AddField(
            model_name='order',
            name='star_num',
            field=models.IntegerField(default=5, verbose_name='评星'),
        ),
    ]
