# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_auto_20200322_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='审核'),
        ),
    ]
