# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-22 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInconfont',
            fields=[
                ('metaId', models.IntegerField(primary_key=True, serialize=False, verbose_name='标签id')),
                ('value', models.CharField(max_length=50, verbose_name='名称')),
                ('classname', models.CharField(max_length=30, verbose_name='字体类名')),
            ],
        ),
    ]
