# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-15 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_housecollection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housecollection',
            options={'verbose_name_plural': '用户收藏'},
        ),
        migrations.RemoveField(
            model_name='housecollection',
            name='status',
        ),
        migrations.AlterField(
            model_name='housecollection',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='收藏时间'),
        ),
    ]
