# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-13 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20200315_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metainconfont',
            options={'verbose_name_plural': '设施图标'},
        ),
    ]
