# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-06 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女'), (None, '保密')], default=None, null=True, verbose_name='性别'),
        ),
    ]
